### ISSUE TITLE
Don't show display (edit: please add support SSD1327)

### ISSUE THREAD

**Issue by ankitatayade87** [alexanderlavrushko/BLE-HUD-navigation-ESP32#17]
I use your v0.2.0 code. and i'm using 1.5 inch OLED module with esp32 nodemcu.pls sir solve my problem
![Screenshot 2021-10-04 162824](https://user-images.githubusercontent.com/52994531/135840130-bf91e2fc-e007-4288-b960-f96423037bb5.jpg)

**Comment by alexanderlavrushko** [comment]
It looks like a problem with uploading. When you upload any other Arduino sketch (new empty sketch, for example) - does it uploads normally?

**Comment by ankitatayade87** [comment]
Yes after uplaod the program OLED display again blank. Please sir can u help me
![Screenshot 2021-10-04 211714](https://user-images.githubusercontent.com/52994531/135882751-bf8c68b1-11bf-48ac-9894-c35caaf30f04.jpg)

**Comment by alexanderlavrushko** [comment]
This log looks good, like a normal successful upload. But your display doesn't show anything? Can you describe which exactly ESP32 module you have, and which pins you connect the display?

**Comment by ankitatayade87** [comment]
NODEMCU ESP32S Wroom.
VCC-5V
GND-GND
DIN-P23
CLK-P18
CS-P5
DC-P17
RST-P16
![WhatsApp Image 2021-10-05 at 22 33 57](https://user-images.githubusercontent.com/52994531/136069815-c6b66c6d-ef4d-47fe-a98c-bab40ea8a6c8.jpeg)

**Comment by alexanderlavrushko** [comment]
As far as I can see from the image, the black wire is not on its place - it must be GND pin, but you have it connected to CMD pin.

<img src="https://user-images.githubusercontent.com/28007228/136078663-a6c7beca-c154-4475-94fb-ac2a450e22ba.jpg" height=400>

**Comment by ankitatayade87** [comment]
I also change GND pins as you show in dig. but again display blank. I also try to upload waveshare site sample code again same problem with display.

**Comment by alexanderlavrushko** [comment]
Serial Monitor looks good, it seems the program works as expected.

I've just noticed that you are using **not the same display** as I do. I use RGB version, you use monochrome version.

1. 1.5inch RGB OLED display Module - https://www.waveshare.com/1.5inch-rgb-oled-module.htm
1. 1.5inch OLED display Module - https://www.waveshare.com/1.5inch-OLED-Module.htm

This project is made for RGB version (they have different communication protocols: SSD1351 and SSD1327 respectively).

Actually I have a monochrome version also, I'll check if it's possible to make the project work with it.

**Comment by ankitatayade87** [comment]
pls, can u do this project on the monochrome version because I have already bought this product?
and I am working on the project it has two handband where RGB module and vibration are placed in those bands which gives turn-turn navigation like (left/right).plss sir can u help me in this project. 
[new.pdf](https://github.com/alexanderlavrushko/BLE-HUD-navigation-ESP32/files/7378411/new.pdf)

**Comment by Jb932164** [comment]
PLEASE sir help me in this project.

**Comment by alexanderlavrushko** [comment]
I have tried my OLED monochrome 1.5" display and it just doesn't work (I have 2 of them, and both don't work), my old code examples which worked a few years ago don't work anymore on these displays, and Adafruit SSD1327 library also does nothing with them, they are just black all the time.

So, as I don't have a working SSD1327 display, I will not work on this.

For you, I can suggest one of these options:
1. get ESP32 TTGO T-Display https://www.aliexpress.com/item/33048962331.html
2. or get a supported display - Waveshare 14747 OLED RGB https://www.waveshare.com/1.5inch-RGB-OLED-Module.htm
3. or try to make your display work with any other project, just to be sure that display works - then you will be able to implement your own drawing of HUD data (so this project will receive navigation data, and you add your own code to show them on your display)

**Comment by Jb932164** [comment]
Hello sir,can this project work on LED display.beacause i'm from India and
here RGB OLED display is not available.please sir.


https://robu.in/product/waveshare-240x240-general-1-54inch-lcd-display-module-ips-65k-rgb/

**Comment by alexanderlavrushko** [comment]
With this ESP32 TTGO module the project will work: https://robu.in/product/ttgo-esp32-wifi-and-bluetooth-development-board-with-1-14-lcd-display/

That display you sent is not supported at the moment.

**Comment by Jb932164** [comment]
Hello sir,
I upload one pdf regarding project on navigation but he use SSD 1306 OLED
display.please check .

**Comment by Jb932164** [comment]
Sir,can you tell me the process of sygic app pair with display .This work
on  android or ios.which apple phone is required??and
Sygic app free or not or does it require some premium subscription?
Please sir answer me .

**Comment by Jb932164** [comment]
sir, please reply to me as soon as possible.

**Comment by alexanderlavrushko** [comment]
At the moment, pairing between the phone and display is not needed, but some day in future I think it will be necessary (for example, if there are 2 displays near the phone, we should connect to the paired one). The application on the phone just scans for BLE devices which contain service with [expected UUID](https://github.com/alexanderlavrushko/BLE-HUD-navigation-ESP32#table-of-uuids).

Currently this project works only with iOS. There is a chance that Android will also be added in first half 2022. At the moment Sygic app doesn't ask for Premium subscription to use this feature, but I think it will be fixed soon (so it will be this way: if you can see turn-by-turn instructions on the phone (Premium or Trial), then you'll also be able to see them on Bluetooth display).

**Comment by Jb932164** [comment]
But I have one doubt that how i connect the esp 32 with sygic app.Suppose i
upload code in esp 32 then what the next process to display my output???
Please sir reply me

**Comment by alexanderlavrushko** [comment]
In the iOS app: Menu / Settings / Info / About / tap 3 times on any item (new line About appears at the top) / About / BLE HUD / Start

Note that it becomes off after the app restart.

For more info, see README.md, section "Application iOS".
